### ISSUE TITLE
Update node-telegram-bot-api to 0.27.0

### ISSUE THREAD

**Issue by ro31337** [GochoMugo/tgfancy#10]
There is a bug https://github.com/yagop/node-telegram-bot-api/issues/281

And this version is dependent on buggy `node-telegram-bot-api`.

I would say it is critical.

**Comment by GochoMugo** [comment]
Sorry, seems dependencies went out of date. Until NTBA hits v1, we will have to keep our dependency version updated to catch up.

See https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004 for more information.

**Comment by ro31337** [comment]
I just created PR with this fix, because seems like it's critical. I got few errors already (Telegram servers unstable?)

**Comment by GochoMugo** [comment]
That underlying error must have been fatal, as the library did not get a server response. Maybe network problem with your server? Can't reach the Telegram servers? Probably something along those lines.

**Comment by GochoMugo** [comment]
This has been fixed in **v0.9.0**.

Thanks @ro31337 for the PR!

We can continue the discussion here, if you wish so.
