### ISSUE TITLE
echo dont work =(

### ISSUE THREAD

**Issue by PinkyRabbit** [GochoMugo/tgfancy#19]
Hello! I trying to use tgfancy but echo dont want to works =(
[Look on my files](https://github.com/PinkyRabbit/my-telegrambot/tree/tgfancy) what I do wrong?

**Comment by GochoMugo** [comment]
Are you sending an argument with the command?  For example, `/echo hello`

**Comment by PinkyRabbit** [comment]
Sorry i had to add `{polling: true}`

**Comment by GochoMugo** [comment]
No problem. :+1:
